/*
# Create ai_decision_history table

1. New Tables
- `ai_decision_history`: Stores the full lifecycle of every AI recommendation
  generated by the Recommendation Engine — from prediction through operator
  action to final outcome. This provides an auditable trail of AI-driven
  logistics decisions.
  - `id` (uuid, primary key)
  - `recommendation_id` (text, unique ID of the recommendation from the engine)
  - `shipment_id` (text, the truck/shipment identifier from the simulation)
  - `shipment_number` (text, human-readable shipment number)
  - `prediction` (text, the AI-generated prediction title)
  - `risk_detected` (text, the risk explanation from the engine)
  - `recommendation_generated` (text, the recommended action text)
  - `operator_action` (text, 'accepted' or 'ignored')
  - `final_outcome` (text, the outcome after the action was taken)
  - `confidence_score` (integer, 0-100 confidence from the engine)
  - `created_at` (timestamptz, when the decision was recorded)

2. Security
- Enable RLS on `ai_decision_history`.
- Allow authenticated users full CRUD (this is a signed-in app with
  role-based access via the auth-guard middleware).
- No user_id column because decisions are system-generated, not user-owned.
  All authenticated operators share the same decision log.
*/

CREATE TABLE IF NOT EXISTS ai_decision_history (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  recommendation_id text NOT NULL,
  shipment_id text NOT NULL,
  shipment_number text NOT NULL,
  prediction text NOT NULL,
  risk_detected text NOT NULL,
  recommendation_generated text NOT NULL,
  operator_action text NOT NULL DEFAULT 'accepted',
  final_outcome text NOT NULL DEFAULT '',
  confidence_score integer NOT NULL DEFAULT 0,
  created_at timestamptz DEFAULT now()
);

ALTER TABLE ai_decision_history ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "select_ai_decision_history" ON ai_decision_history;
CREATE POLICY "select_ai_decision_history"
ON ai_decision_history FOR SELECT
TO authenticated USING (true);

DROP POLICY IF EXISTS "insert_ai_decision_history" ON ai_decision_history;
CREATE POLICY "insert_ai_decision_history"
ON ai_decision_history FOR INSERT
TO authenticated WITH CHECK (true);

DROP POLICY IF EXISTS "update_ai_decision_history" ON ai_decision_history;
CREATE POLICY "update_ai_decision_history"
ON ai_decision_history FOR UPDATE
TO authenticated USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS "delete_ai_decision_history" ON ai_decision_history;
CREATE POLICY "delete_ai_decision_history"
ON ai_decision_history FOR DELETE
TO authenticated USING (true);

CREATE INDEX IF NOT EXISTS idx_ai_decision_history_shipment ON ai_decision_history(shipment_id);
CREATE INDEX IF NOT EXISTS idx_ai_decision_history_created ON ai_decision_history(created_at DESC);
